import { describe, it, expect, vi, beforeEach } from "vitest";
import { generateKeyPairSync, sign } from "crypto";
import { deviceService } from "../../src/modules/devices/device.service.js";
import * as dbClient from "../../src/infra/database/client.js";

vi.mock("../../src/infra/database/client.js", () => ({
  query: vi.fn(),
}));

describe("DeviceService", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("registerDevice", () => {
    it("should register a device and return a challenge", async () => {
      const mockDeviceId = "grandma-android-device-001";
      const { publicKey } = generateKeyPairSync("rsa", {
        modulusLength: 2048,
        publicKeyEncoding: { type: "spki", format: "pem" },
        privateKeyEncoding: { type: "pkcs8", format: "pem" },
      });

      // 1. Mock DB insert query
      vi.mocked(dbClient.query).mockResolvedValueOnce({
        rows: [
          {
            id: "dev-uuid-1",
            device_id: mockDeviceId,
            public_key: publicKey,
            device_metadata: { model: "Pixel 6" },
            is_verified: false,
            status: "active",
            created_at: new Date(),
            updated_at: new Date(),
          },
        ],
        rowCount: 1,
        command: "INSERT",
        oid: 0,
        fields: [],
      });

      // 2. Mock DB select query inside createChallenge
      vi.mocked(dbClient.query).mockResolvedValueOnce({
        rows: [{ id: "dev-uuid-1" }],
        rowCount: 1,
        command: "SELECT",
        oid: 0,
        fields: [],
      });

      const result = await deviceService.registerDevice({
        deviceId: mockDeviceId,
        publicKey,
        deviceMetadata: { model: "Pixel 6" },
      });

      expect(result.device.deviceId).toBe(mockDeviceId);
      expect(result.device.isVerified).toBe(false);
      expect(typeof result.challenge).toBe("string");
      expect(result.challenge.length).toBe(64); // 32 bytes in hex
    });
  });

  describe("verifySignature", () => {
    it("should verify valid signature generated by device private key", async () => {
      const mockDeviceId = "grandma-android-device-001";

      // Generate actual RSA KeyPair for testing
      const { publicKey, privateKey } = generateKeyPairSync("rsa", {
        modulusLength: 2048,
        publicKeyEncoding: { type: "spki", format: "pem" },
        privateKeyEncoding: { type: "pkcs8", format: "pem" },
      });

      const challenge = "a1b2c3d4e5f67890123456789abcdef0a1b2c3d4e5f67890123456789abcdef0";

      // Sign the challenge with private key
      const signatureBuffer = sign("sha256", Buffer.from(challenge, "utf-8"), privateKey);
      const signatureBase64 = signatureBuffer.toString("base64");

      // Mock DB select query to return public key
      vi.mocked(dbClient.query).mockResolvedValueOnce({
        rows: [
          {
            id: "dev-uuid-1",
            device_id: mockDeviceId,
            public_key: publicKey,
            is_verified: false,
          },
        ],
        rowCount: 1,
        command: "SELECT",
        oid: 0,
        fields: [],
      });

      // Mock DB update query setting is_verified = true
      vi.mocked(dbClient.query).mockResolvedValueOnce({
        rows: [],
        rowCount: 1,
        command: "UPDATE",
        oid: 0,
        fields: [],
      });

      const verification = await deviceService.verifySignature({
        deviceId: mockDeviceId,
        challenge,
        signature: signatureBase64,
      });

      expect(verification.verified).toBe(true);
      expect(verification.message).toContain("successfully verified");
      expect(dbClient.query).toHaveBeenCalledTimes(2);
    });

    it("should reject invalid signature signed with wrong key", async () => {
      const mockDeviceId = "grandma-android-device-001";

      const { publicKey } = generateKeyPairSync("rsa", {
        modulusLength: 2048,
        publicKeyEncoding: { type: "spki", format: "pem" },
        privateKeyEncoding: { type: "pkcs8", format: "pem" },
      });

      const wrongKeyPair = generateKeyPairSync("rsa", {
        modulusLength: 2048,
        publicKeyEncoding: { type: "spki", format: "pem" },
        privateKeyEncoding: { type: "pkcs8", format: "pem" },
      });

      const challenge = "a1b2c3d4e5f67890123456789abcdef0a1b2c3d4e5f67890123456789abcdef0";

      // Sign with wrong private key
      const wrongSignature = sign("sha256", Buffer.from(challenge, "utf-8"), wrongKeyPair.privateKey).toString("base64");

      vi.mocked(dbClient.query).mockResolvedValueOnce({
        rows: [
          {
            id: "dev-uuid-1",
            device_id: mockDeviceId,
            public_key: publicKey, // Original public key
            is_verified: false,
          },
        ],
        rowCount: 1,
        command: "SELECT",
        oid: 0,
        fields: [],
      });

      const verification = await deviceService.verifySignature({
        deviceId: mockDeviceId,
        challenge,
        signature: wrongSignature,
      });

      expect(verification.verified).toBe(false);
      expect(verification.message).toContain("Invalid signature");
    });
  });
});
